# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_queue_default_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True, verbose_name='Optional actions to perform for recipient'),
        ),
    ]
